### ISSUE TITLE
MenuSlideBar 

### ISSUE THREAD

**Issue by MijeongJeon** [FCSProjectAirMap/FCSProjectAirMap_iOS#32]
<img width="257" alt="screen shot 2016-07-15 at 9 27 58 pm" src="https://cloud.githubusercontent.com/assets/19141925/16874217/0a40ef2e-4ad3-11e6-9b92-b27878f5b1b7.png">

@Tedigom 얘네 수정 부탁드려요~

**Comment by wngus606** [comment]
@Tedigom 수정 부탁드려요~
