### ISSUE TITLE
travel_title_unique를 primary_key로 업데이트필요!?

### ISSUE THREAD

**Issue by MijeongJeon** [FCSProjectAirMap/FCSProjectAirMap_iOS#68]
<img width="1090" alt="screen shot 2016-07-26 at 6 50 04 am" src="https://cloud.githubusercontent.com/assets/19141925/17118797/4f0ae1e6-52fd-11e6-93bc-b5b26b4b030d.png">

Q. 이미 램에 저장되어있는 여행경로가 있을때, 서버에서 경로 정보가 덮어 씌어지지 않고 새롭게 생성되는 문제
A? 프라이머리 키값이 필요하지 않을까? 혹은 travel_title값 제거?

**Comment by wngus606** [comment]
1. travel_title_unique를 primary_key로 생각은 했는데... 그부분은 또다른 문제가 생길까봐 일단 놔둔상태임.
2. 지금 새롭게 생성되는 문제는 realm에 저장하는 로직을 봐야할꺼 같음.
